### ISSUE TITLE
Query error while filtering volumes

### ISSUE THREAD

**Issue by nutria007** [bacula-web/bacula-web#101]
**Describe the bug**

**To Reproduce**
1. Go to 'Volumes report'
2. Click on 'Pool dropdown'
3. Select a pool
4. Click on 'Apply'
5. Error page is displayed

**Expected behavior**
Filtered list displayed.

**Error page**
Details
A problem with the description below happen

Problem: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':pool_id' at line 1
Debug
File: /var/www/bacula/core/app/cmodel.class.php
Line: 138
Code: 42000
Exception trace
File: /var/www/bacula/core/app/cmodel.class.php on line 138 in function PDOStatement->execute
File: /var/www/bacula/core/app/cmodel.class.php on line 67 in function CModel->run_query
File: /var/www/bacula/application/models/volumes.model.php on line 30 in function CModel->count
File: /var/www/bacula/application/views/volumes.view.php on line 128 in function Volumes_Model->count
File: /var/www/bacula/core/app/webapplication.class.php on line 136 in function VolumesView->prepare
File: /var/www/bacula/index.php on line 21 in function WebApplication->run

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser : chrome
 - Version 97.0.4692.71
 - PHP version 7.4

**Additional context**

**Comment by dfranco** [comment]
Thanks @nutria007 for this bug report, 
a bug (#99 ) has already been created and I'm working on a fix.
Please be patient as the fix needs a bit of time.

**Comment by dfranco** [comment]
Hello @Githopp192 ,

Thanks for the bug report.

It's similar to #99, I'm working on a fix when I have time.

Best,

**Comment by Githopp192** [comment]
Hey Franco, no stress on that :-) .. 8.5.1 seems to work quite well - so no urgency at all.

Thx 4 your great work on that !
Cheers
Mike

**Comment by dfranco** [comment]
Hello @Githopp192,

This issue is now fixed, a new release will be available soon.

Thanks again for your bug report.

**Comment by Githopp192** [comment]
Very welcome & thx a lot Franco. Wish you a great time in hard times.
Best Mike
