### ISSUE TITLE
Division by zero with canceled jobs inBackup Job report

### ISSUE THREAD

**Issue by Helmut1972** [bacula-web/bacula-web#105]
**Describe the bug**
If I chose more than 1 week for a backup report the application throws an error:

Fatal error: Uncaught DivisionByZeroError: Division by zero in /var/www/bacula-web/application/views/backupjob.view.php:177 Stack trace: #0 /var/www/bacula-web/core/app/webapplication.class.php(136): BackupJobView->prepare() #1 /var/www/bacula-web/index.php(21): WebApplication->run() #2 {main} thrown in /var/www/bacula-web/application/views/backupjob.view.php on line 177

**Desktop (please complete the following information):**
 - OS: FreeBSD 12.3
 - Browser Chrome
 - Version 8.5.2
 - PHP version 8.0

**Additional context**
```
// Compression
if ($job['jobbytes'] > 0) {
  $compression = (1-($job['jobbytes'] / $job['readbytes']));
  $job['compression'] = number_format($compression, 2);
} else {
  $job['compression'] = 'N/A';
}
```

It might make sense to sanity check $job['readbytes'], too:

`if (($job['jobbytes'] > 0) and ($job['readbytes'] > 0)){`

In my case I have some cancelled jobs with 0 Bytes read.

![2022_02_27_17_56_Bacula_Web_Backup_job_report](https://user-images.githubusercontent.com/35489776/155891809-67fa32b3-84bd-4635-8e6c-f125e7eb834a.jpg)
.

**Comment by dfranco** [comment]
Thanks for this bug report @Helmut1972 .

This fix will be included in next release.
