### ISSUE TITLE
SQL query error using custom datetime format in Client report page

### ISSUE THREAD

**Issue by Helmut1972** [bacula-web/bacula-web#106]
**Describe the bug**
When using a different time format Bacula Web throws an error when trying to generate a Client report.

`Details
A problem with the description below happen

Problem: SQLSTATE[HY000]: General error: 1525 Incorrect DATETIME value: '22.02.2022 00:00:00'
Debug
File: /var/www/bacula-web/core/app/cmodel.class.php
Line: 138
Code: HY000
Exception trace
File: /var/www/bacula-web/core/app/cmodel.class.php on line 138 in function PDOStatement->execute
File: /var/www/bacula-web/application/views/client.view.php on line 131 in function CModel->run_query
File: /var/www/bacula-web/core/app/webapplication.class.php on line 136 in function ClientView->prepare
File: /var/www/bacula-web/index.php on line 21 in function WebApplication->run`

**Desktop (please complete the following information):**
 - OS: FreeBSD 12.3
 - Browser Chrome
 - Version 8.5.2
 - PHP version 8.0

**Comment by dfranco** [comment]
The code was using the custom datetime format to build the SQL query, it should use the "default" datetime format ("Y-m-d H:i:s") instead.

This is now fixe and will be included in next release.

Thanks for your bug report @Helmut1972
