### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by gligorco** [bacula-web/bacula-web#112]
Hi,

I just installed bacula-web, and raise problem with "invalid data source name".
attached is the screenshot. Can you help me to fix problem. I have installed bacula on ubuntu 20.3 with postgresql 12.11
Thanks. Gligor

![bacula-web-invalid data source](https://user-images.githubusercontent.com/81472340/179743922-04eaf9d9-df1b-4e17-a1d0-b02460184aa0.png)

**Comment by gligorco** [comment]
Hi @dfranco ,

I found and solved my problem in config.php.
This error appear due to wrong address in pgsql section. I repaired and now is working well.
But this web interface is only for reporting... is there any plug in for backup management and administration?

Thank you.

Gligor

**Comment by dfranco** [comment]
Hi @gligorco ,

Happy to know that you've fixed your configuration problem.

Regarding backup management and administration, Bacula-Web is mainly a "reporting only" web interface. But more options will come in future releases.

Best,
