### ISSUE TITLE
smarty on FreeBSD?

### ISSUE THREAD

**Issue by lrosenman** [bacula-web/bacula-web#130]
**Describe the bug**
I'm the maintainer for FreeBSD, and running composer garnered:
❯ cd /usr/local/www/bacula-web; sudo composer i
zsh: correct 'composer' to '.composer' [nyae]? n
Do not run Composer as root/super user! See https://getcomposer.org/root for details
You are using Composer 1 which is deprecated. You should upgrade to Composer 2, see https://blog.packagist.com/deprecating-composer-1-support/
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for smarty/smarty v3.1.47 -> satisfiable by smarty/smarty[v3.1.47].
    - smarty/smarty v3.1.47 requires php ^5.2 || ^7.0 -> your PHP version (8.0.24) does not satisfy that requirement.

ler in 🌐 borg in local/www/bacula-web🔒 via 🐘 v8.0.24 on ☁️  (us-east-1)
❯

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=267385

**To Reproduce**
Install port, run composer

**Expected behavior**
working install.

**Desktop (please co
 - FreeBSD 14
 - N/A
 - Version 14 (probably 13.1 as well)
 - PHP 8.0,24

**Additional context**

**Comment by lrosenman** [comment]
I can provide access to my server if needed.

**Comment by dfranco** [comment]
Hi @lrosenman ,

Thanks for the bug report.

> I can provide access to my server if needed.

It would be useful as I don't have access to a FreeBSD server in my dev environment.

Please let me know by email how we can arrange access to your server.

Best,

**Comment by lrosenman** [comment]
Email address?

**Comment by dfranco** [comment]
You can use the one I use on bacula-users mailing list

**Comment by dfranco** [comment]
I sent you an email @lrosenman

**Comment by dfranco** [comment]
Issue #131 created based on your issue @lrosenman

**Comment by dfranco** [comment]
Hello @lrosenman ,

I manage to fix this issue and confirm the fix on FreeBSD 14 (tested on Ubuntu 22.04, Debian 11 + Debian 10).

Now I need to run a couple of other tests, update the documentation and fixes some stuff before releasing another version.

I have documented a "workaround" in #131 if other users wants to use v8.6.2

**Comment by lrosenman** [comment]
Any news on a new release?

**Comment by dfranco** [comment]
> Any news on a new release?

I'd need a couple more days before publishing the new release, as they're few stuff I'd like to fix before v8.6.3.

**Comment by dfranco** [comment]
Hi @lrosenman ,

Release v8.6.3 has been published.

I'm closing this one as it works fine now on FreeBSD 14 with PHP 8.0.
