### ISSUE TITLE
Documentation for update (Smarty Cache directory)

### ISSUE THREAD

**Issue by sruckh** [bacula-web/bacula-web#139]
the `bwc check` says that the smarty cache directory needs to be writeable by web user.  The application/views/cache/ directory is not mentioned in the Upgrade portion of the documentation.  If it needs to be writeable by web user, please include that directory in the documentation.

**Comment by dfranco** [comment]
Hi @sruckh ,

Thanks for this new issue

Quick question before I check the doc, could you clarify how you've done the first installation ?

- from the source tar.gz
- from the bacula-web-x.y.z.tgz
- from source (using git clone ....)

**Comment by dfranco** [comment]
Any feedback @sruckh ?

**Comment by dfranco** [comment]
Hello @sruckh ,

> the `bwc check` says that the smarty cache directory needs to be writeable by web user. The application/views/cache/ directory is not mentioned in the Upgrade portion of the documentation. If it needs to be writeable by web user, please include that directory in the documentation.

There's no need to include it in the upgrade documentation as it's already covered by the installation chapter/section.

I'm closing this one since I haven't received a feedback from you anyway.
