### ISSUE TITLE
centos 7.9:upgrade php-7.4 to php-8.2 (remi)

### ISSUE THREAD

**Issue by Githopp192** [bacula-web/bacula-web#152]
**Describe the bug**

tried to upgrade from php-7.4 to php-8.2 (remi)

Other http/web applications are properlly working after upgrade to php 8.2, like: 

- webmin
- baculum
   

**To Reproduce**
1. remove php 7.4
2. install php 8.2 (remi)

**Expected behavior**
got http error 500 - web page should open

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser :newest MS Edge
 - PHP version remi php-8.2

**Additional context**
[Sat Feb 18 11:29:44.997476 2023] [php:error] [pid 19709] [client xxx] PHP Fatal error:  Uncaught TypeError: Attribute value must be of type bool for selected attribute, 
array given in /var/www/html/baculaweb/core/db/Database.php:73\nStack trace:\n#0 /var/www/html/baculaweb/core/db/Database.php(73):
PDO->__construct()\n#1 /var/www/html/baculaweb/core/db/DatabaseFactory.php(31): Core\\Db\\Database->__construct()\n#2 
/var/www/html/baculaweb/application/views/dashboard.view.php(54): Core\\Db\\DatabaseFactory::getDatabase()\n#3 /var/www/html/baculaweb/core/app/webapplication.class.php(260):
App\\Views\\DashboardView->prepare()\n#4 /var/www/html/baculaweb/public/index.php(27): 
Core\\App\\WebApplication->run()\n#5 {main}\n\nNext Error: Call to a member function send() on null in /var/www/html/baculaweb/core/app/webapplication.class.php:274\nStack 
trace:\n#0 /var/www/html/baculaweb/public/index.php(27): Core\\App\\WebApplication->run()\n#1 {main}\n  thrown in /var/www/html/baculaweb/core/app/webapplication.class.php on line 274

php-(8.2) Modules:

[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
ldap
libxml
mcrypt
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
random
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
zlib

**Comment by dfranco** [comment]
Thanks for the bug report @Githopp192

**Comment by Githopp192** [comment]
very welcome
