### ISSUE TITLE
Columns like bytes, files, and speed should be right justified

### ISSUE THREAD

**Issue by sruckh** [bacula-web/bacula-web#162]
On job reports page, or anywhere that column formatting is used, I believe visually, columns like bytes, files, and speed would look cleaner if they were right justified.  Also as reported in another bug report, the file column on job reports page is also using periods instead of comma.

**Comment by dfranco** [comment]
Thanks for the suggestion @sruckh 

I'll make some fixes and see if this change makes those column more readable.

I'll keep you posted

**Comment by dfranco** [comment]
I agree, I'll make a fix for next version
