### ISSUE TITLE
Error while using start and end time with other filter options

### ISSUE THREAD

**Issue by sruckh** [bacula-web/bacula-web#167]
![bweb-query](https://user-images.githubusercontent.com/29985975/227311120-c804b73d-7f4e-4216-97ef-f6cbb58e0698.png)
Any query I run from the Jobs Report screen (and use start/stop times) gives an Oops Database error.  Example query given in attached screen shot.

**To Reproduce**
Open job reports screen.  Run a query with start-time as one of the parameters.

**Expected behavior**
Return proper results from query.

**Screenshots**
Screen Shot Attached.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Bacula-Web running on CentOS 7.9 server with MariDB database.
 - Browser [e.g. chrome, safari] IE Edge browser
 - Version [e.g. 8.5]  Bacula web 8.8.0 / Edge server: Version 111.0.1661.51 (Official build) (64-bit)
 - PHP version [e.g. 7.3] PHP 7.4.33

**Additional context**

**Comment by dfranco** [comment]
Thanks for the bug report @sruckh 

I was able to reproduce the issue
Setting start date and end date only does works, but as soon as I choose a specific client or pool, there's a PHP PDO exception.

I'll fix this asap.

**Comment by sruckh** [comment]
Thank You.

**Comment by dfranco** [comment]
with pleasure, I'm working on pubishing another release which should be available really soon.
