### ISSUE TITLE
Blank Screen after install

### ISSUE THREAD

**Issue by dmidthun** [bacula-web/bacula-web#170]
**Describe the bug**
page(es?) is not rendered when browsed
**To Reproduce**
1. Go to 'http://i.p.address'
2. See error

**Expected behavior**
pages rendered

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win 11
 - Browser [e.g. chrome, safari] Edge, Chrome, Firefox
 - Version [e.g. 8.5]
 - PHP version [e.g. 7.3] 8.1

**Additional context**
available for remote session to see problem

**Comment by dfranco** [comment]
Hi @dmidthun 

Could you tell me how you installed Bacula-Web ?
Composer or Docker ?

Blank page means PHP fatal error, could you enable debug mode and share the error please ?

**Comment by dmidthun** [comment]
@dfranco thanks for getting back to me - I used the composer install.

on which would you like debug, the configuration for the app, or from php?

**Comment by dfranco** [comment]
> @dfranco thanks for getting back to me - I used the composer install.
> 
> on which would you like debug, the configuration for the app, or from php?

in Bacula-Web configuration, you can use the [the documentation](https://docs.bacula-web.org/en/latest/02_install/configure.html#debug)

> by enabling debug mode in Bacula-Web config, it enable PHP debug mode too.

**Comment by dmidthun** [comment]
debug mode is on -- im not getting a log, unless im looking in the wrong spot?

**Comment by dfranco** [comment]
Can you try to run check from the console ?

https://docs.bacula-web.org/en/latest/02_install/test.html#using-bacula-web-console

**Comment by dmidthun** [comment]
root@virt-backup:/var/www/bacula-web# sudo -u www-data php bwc check
=====================
Checking requirements
=====================

	PHP version Ok (using 8.1.2-1ubuntu2.11)
	PHP timezone Ok
	Protected assets folder is writable Ok
	Smarty cache folder write permission Ok

Checking installed PHP database extensions
==========================================

	pgsql installed
	sqlite installed

Checking installed PHP extensions
=================================

	SQLite support Ok
	Gettext support Ok
	Session support Ok
	PHP PDO support Ok
	PHP Posix support Ok

root@virt-backup:/var/www/bacula-web#

**Comment by dfranco** [comment]
Strange, everything seems ok

Can I have access to the host so I can troubleshoot ?

**Comment by dmidthun** [comment]
sure - Im setting up a zoom meeting

**Comment by dmidthun** [comment]
https://us04web.zoom.us/s/75389245510

**Comment by dmidthun** [comment]
should be good now

**Comment by dfranco** [comment]
I'm in

**Comment by dmidthun** [comment]
`root@virt-backup:/var/www/bacula-websudo -u www-data composer install
Loading "robloach/component-installer" which is a legacy composer-installer built for Composer 1.x, it is likely to cause issues as you are running Composer 2.x.
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package robloach/component-installer is abandoned, you should avoid using it. Use oomphinc/composer-installers-extender instead.
Package sebastian/phpcpd is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
> ComponentInstaller\Installer::postAutoloadDump
Compiling component files
Deprecation Notice: Return type of Assetic\Asset\AssetCollectionFilterIterator::getChildren() should either be compatible with RecursiveFilterIterator::getChildren(): ?RecursiveFilterIterator, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/bacula-web/vendor/kriswallsmith/assetic/src/Assetic/Asset/AssetCollection.php:226
Deprecation Notice: Return type of Assetic\Asset\AssetCollectionFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/bacula-web/vendor/kriswallsmith/assetic/src/Assetic/Asset/AssetCollection.php:196
Deprecation Notice: Return type of Assetic\Asset\AssetCollection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/bacula-web/vendor/kriswallsmith/assetic/src/Assetic/Asset/AssetCollection.php:153
Deprecation Notice: Return type of Assetic\Asset\AssetCollectionIterator::hasChildren() should either be compatible with RecursiveIterator::hasChildren(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/bacula-web/vendor/kriswallsmith/assetic/src/Assetic/Asset/AssetCollection.php:314
Deprecation Notice: Return type of Assetic\Asset\AssetCollectionIterator::getChildren() should either be compatible with RecursiveIterator::getChildren(): ?RecursiveIterator, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/bacula-web/vendor/kriswallsmith/assetic/src/Assetic/Asset/AssetCollection.php:322
Deprecation Notice: Return type of Assetic\Asset\AssetCollectionIterator::current($raw = false) should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/bacula-web/vendor/kriswallsmith/assetic/src/Assetic/Asset/AssetCollection.php:267
Deprecation Notice: Return type of Assetic\Asset\AssetCollectionIterator::next() should either be compatible with Iterator::next(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/bacula-web/vendor/kriswallsmith/assetic/src/Assetic/Asset/AssetCollection.php:299
Deprecation Notice: Return type of Assetic\Asset\AssetCollectionIterator::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/bacula-web/vendor/kriswallsmith/assetic/src/Assetic/Asset/AssetCollection.php:294
Deprecation Notice: Return type of Assetic\Asset\AssetCollectionIterator::valid() should either be compatible with Iterator::valid(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/bacula-web/vendor/kriswallsmith/assetic/src/Assetic/Asset/AssetCollection.php:309
Deprecation Notice: Return type of Assetic\Asset\AssetCollectionIterator::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/bacula-web/vendor/kriswallsmith/assetic/src/Assetic/Asset/AssetCollection.php:304
Deprecation Notice: Return type of Assetic\Filter\FilterCollection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/bacula-web/vendor/kriswallsmith/assetic/src/Assetic/Filter/FilterCollection.php:73
Deprecation Notice: Return type of Assetic\Filter\FilterCollection::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/bacula-web/vendor/kriswallsmith/assetic/src/Assetic/Filter/FilterCollection.php:78
Deprecation Notice: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/bacula-web/vendor/kriswallsmith/assetic/src/Assetic/Asset/AssetCollection.php:255
Deprecation Notice: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/bacula-web/vendor/kriswallsmith/assetic/src/Assetic/Asset/AssetCollection.php:255
Deprecation Notice: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/bacula-web/vendor/kriswallsmith/assetic/src/Assetic/Asset/AssetCollection.php:255
Deprecation Notice: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/bacula-web/vendor/kriswallsmith/assetic/src/Assetic/Asset/AssetCollection.php:255
55 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> php bwc publishAssets
Publishing assets
`

**Comment by dmidthun** [comment]
Davide,

  It appears that the application is working now! I re-ran the composer script, changed the permissions on the folder, and ran the checks, and it's working! Thank you so much for your time and hard work!!! I love it!

  Dan

**Comment by dfranco** [comment]
Great news! Really happy for you

**Comment by dfranco** [comment]
If there's something to improve or fix, don't hesitate to open another issue here. Closing this one
