### ISSUE TITLE
Pools and Volume status legend overlapping chart

### ISSUE THREAD

**Issue by sruckh** [bacula-web/bacula-web#173]
**Describe the bug**
The format/layout of Pools and Volume Status with Pie Graph is messy.  Probably need to lower the pie graph.

**To Reproduce**
Open Main Page

**Expected behavior**
Pie Graph and labels not to be on top of one another

**Screenshots**
See attached Screenshot

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser [edge]
 - Version [8.9.0]
 - PHP version [e.g. 7.4.33]

**Additional context**
![bacula-web-PoolsVolume](https://user-images.githubusercontent.com/29985975/234437971-b34e5cba-0465-4e3f-ac79-884cc22fa68a.png)

**Comment by dfranco** [comment]
Thanks for the bug report @sruckh 

This one will be fixed after changing chart library

**Comment by dfranco** [comment]
Still using novus/nvd3, but found a way to right align the legend for pie charts, so it doesn't overlap.
