### ISSUE TITLE
Client agent not able to connect to bacula director

### ISSUE THREAD

**Issue by Stanley2911** [bacula-web/bacula-web#174]
I have installed bacula community version 13.0.3. I have installed Bacula client on a VM. The ping between VM & bacula server is working. But the client side agent is not able to connect to Bacula director on Bacula server at port 9102, i am getting the following error

Connecting to Director 10.29.29.49:9102
Director authorization problem.
Most likely the passwords do not agree.
If you are using TLS, there may have been a certificate validation error during the TLS handshake.

**Comment by dfranco** [comment]
Hi,
This bug tracker is not for Bacula project, I'd suggest you use their bug tracker or ask in Bacula-Users mailing list.
