### ISSUE TITLE
Bacula-Web Docker - Setup user authentication database

### ISSUE THREAD

**Issue by plonxyz** [bacula-web/bacula-web#178]
**Describe the bug**
As written in the instructions I used the command below to create a user:

mkdir protected
docker run --rm -it -u www-data \
  -v $PWD/protected:/var/www/html/application/assets/protected \
  baculaweb/bacula-web:latest php bwc setupauth
  
 It's now time to setup the application back-end database

Please note that all informations stored in the user database will be destroyed
Can we proceed ?

Answer (Yes/No): yes
Let's go !
Deleting application back-end database
Creating database schema
Database error SQLSTATE[HY000] [14] unable to open database file code(14)

**To Reproduce**

run the command
**Expected behavior**
Creating an User for the UI 

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Browser [e.g. chrome, safari] N/A
 - Version [e.g. 8.5] Latest docker container
 - PHP version [e.g. 7.3] N/A

**Additional context**

**Comment by dfranco** [comment]
@plonxyz I have to fix an issue before publishing latest docker image version.

**Comment by plonxyz** [comment]
@dfranco , no worries was able to do a workaround :)

**Comment by plonxyz** [comment]
@dfranco , no worries was able to do a workaround :)

**Comment by dfranco** [comment]
> @dfranco , no worries was able to do a workaround :)

Latest docker image is now available
