### ISSUE TITLE
Using Apache alias results in non-functional installation

### ISSUE THREAD

**Issue by hoover67** [bacula-web/bacula-web#179]
Hello Davide, 

I followed the install instructions, set up the database connection but trying to access bacula-web results in an error message. 

I've added an Alias to /var/www/html/bacula-web as /bacula-web in apache2 on Ubuntu 22.04. 

Apparently index.php lives in public/index.php, but if I try to access https:<host>/bacula-web/public/index.php

I'm seeing an error message. Also, the provided "test" link on the error page does not work. 

I've set up earlier versions of bacula-web (pre-composer) dozens of times without issues, but not this time. Please advise :-) 

![image](https://github.com/bacula-web/bacula-web/assets/16132170/a54649bc-5fc6-452e-b3fc-0b06084496a5)

All the best, 

Uwe

**Comment by hoover67** [comment]
URL above is correct, I just reducted the hostname :-)

**Comment by dfranco** [comment]
Hi @hoover67 

Could you share Apache config please ?

I'll try to reproduce the issue

**Comment by hoover67** [comment]
Hello Davide,

it's very simple (just an Alias entry really). The server also runs moodle
and a few wordpress instances so everything should be ok on the php side.

I've tried aliasing the main bacula-web dir (which has no index.php at all)
and the "public" subdirectory.

Cheers, Uwe

**Comment by dfranco** [comment]
@hoover67 what do mean by "aliasing" ? I don't get it

**Comment by dfranco** [comment]
As the requested path is important, DocumentRoot should point to public/index.php

**Comment by dfranco** [comment]
@hoover67 i may have found a way to run Bacula-web in a sub folder, I'll keep you posted.

**Comment by hoover67** [comment]
Thanks Davide!

Uwe

**Comment by mfavetti** [comment]
i had this same issue upgrading to 9,  i've also had bacula-web installed for a long time, and run into problems upgrading along the way with things that I didn't notice had changed until something broke.

If you look here: https://docs.bacula-web.org/en/latest/02_install/nginx-installation.html#configure-nginx the last location block allows path based routing to work. My nginx config was missing that. Once I added it and reloaded nginx, the app worked. Looking at the bacula-web docs for apache, I don't see the equivalent config listed. So I'm not sure how that would be configured in apache. But I think that your problem is the path based routing isn't working.

**Comment by mfavetti** [comment]
Oh, it's here: https://github.com/bacula-web/bacula-web/blob/master/public/.htaccess

Do you have mod_rewrite enabled?

**Comment by dfranco** [comment]
> Oh, it's here: https://github.com/bacula-web/bacula-web/blob/master/public/.htaccess
> 
> Do you have mod_rewrite enabled?

Indeed, mod_rewrite must be enabled.

**Comment by dfranco** [comment]
Thanks @mfavetti for your help

@hoover67 I've found out why it doesn't work while using bacula-web in a subfolder, to make it works will need a bit of time and a lot of tests. I'll create a dedicate branch from which you can test.
I'll start working on that asap.

**Comment by dfranco** [comment]
@hoover67 I'm quiet ready with branch feat/subpath.

While doing last checks on my side, I'd appreciate if you have a try on your side, any feedback would be helpful for sure.

From branch feat/subpath, the only thing you need is add this to application/config/config.php

`$config['basepath'] = '/bacula-web';`

Make sure to not forget the starting slash and adapt it to your setup.

Looking forward to get your feedback(s).

**Comment by hoover67** [comment]
Hello Davide,

thanks for the update, I'll have a look over the next few days.

Cheers, Uwe

**Comment by dfranco** [comment]
@hoover67 As I need to release a new version soon and don't want to "fight" with huge rebase conflicts, I've merged the feature branch (feat/subpath) into master branch.

I let you the time for testing from master, add as many comment/feedback you need here.

**Comment by dfranco** [comment]
Any feedback @hoover67 ?

Where you able to test latest version ?
