### ISSUE TITLE
explode() second argument must be a string if datetime_fomat is commented out in config.php

### ISSUE THREAD

**Issue by markfaine** [bacula-web/bacula-web#185]
This happens with Reports->Jobs and Reports->Volumes
If you have datetime_fomat commented out in your config.php it will return null and the second argument to explode has to be a string.  Should probably set a default value if no value is set.

**Comment by markfaine** [comment]
Also, just now seeing

date(): Argument #1 ($format) must be of type string, null given

on Reports->Backup Job, (Select  Job), Click on Reports.  

Might be related, I can create a separate issue if necessary.

**Comment by dfranco** [comment]
Thanks for this bug report @markfaine 

datetime_format is not supposed to be commented out in config.php, this is where the default format is stored.
The goal to store it in config.php is to make people able to change the default date time format.

I agree for datetime_format_short, in previous versions, it used to be "dynamically" set based on datetime_format but looking at current code, it's not the case anymore. I'll fix that.

Quick win: you shouldn't comment out datetime_format as it's going to break the app as you've already noticed.
For the future, what could be possible is to implement a way to define a default date/time format even it's not part of the configuration (config.php).

Any feedback or comments are welcome :)

**Comment by markfaine** [comment]
> Thanks for this bug report @markfaine
> 
> datetime_format is not supposed to be commented out in config.php, this is where the default format is stored. The goal to store it in config.php is to make people able to change the default date time format.
> 
> I agree for datetime_format_short, in previous versions, it used to be "dynamically" set based on datetime_format but looking at current code, it's not the case anymore. I'll fix that.
> 
> Quick win: you shouldn't comment out datetime_format as it's going to break the app as you've already noticed. For the future, what could be possible is to implement a way to define a default date/time format even it's not part of the configuration (config.php).
> 
> Any feedback or comments are welcome :)

I didn't comment it out.  It's always been commented out.  I had to go in and specifically uncomment it.

**Comment by dfranco** [comment]
> > Thanks for this bug report @markfaine
> 
> > 
> 
> > datetime_format is not supposed to be commented out in config.php, this is where the default format is stored. The goal to store it in config.php is to make people able to change the default date time format.
> 
> > 
> 
> > I agree for datetime_format_short, in previous versions, it used to be "dynamically" set based on datetime_format but looking at current code, it's not the case anymore. I'll fix that.
> 
> > 
> 
> > Quick win: you shouldn't comment out datetime_format as it's going to break the app as you've already noticed. For the future, what could be possible is to implement a way to define a default date/time format even it's not part of the configuration (config.php).
> 
> > 
> 
> > Any feedback or comments are welcome :)
> 
> 
> 
> I didn't comment it out.  It's always been commented out.  I had to go in and specifically uncomment it.

Thanks, I'll make sure it's not commented out then
