### ISSUE TITLE
setupauth password length differs password length in LoginController

### ISSUE THREAD

**Issue by Kunzol** [bacula-web/bacula-web#190]
**Describe the bug**
The setupauth command requests minimum password length of 6 chars. 

LoginController requires password length of 8 chars. 

**To Reproduce**
1. use `sudo -u www-data php bwc setupauth` to create a user with a password of length 7. 
2.  Try to login with the created user and password, which will fail. 

**Expected behavior**
If setupauth is does not complain about the password, it should be possible to login with the password.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3
 - PHP version: 8.1.2

**Comment by dfranco** [comment]
Thanks @Kunzol , I'll will fix this soon

**Comment by dfranco** [comment]
Fixed, password should be at least 8 characters long for both login and bwc setupauth.

Thanks again @Kunzol for the bug report.
