### ISSUE TITLE
Upgrade to 9.2.0 did not work.

### ISSUE THREAD

**Issue by sruckh** [bacula-web/bacula-web#196]
**Describe the bug**
I tried upgrading from v8.9.0 to v9.2.0 using previous upgrade methods and it does not appear to work.  I downloaded v9.2.0 (as tarball).   I backed up working 8.90 version.  I extracted v9.20.

I ran  these commands:
cp -pv bacula-web-beforeupgrade/application/config/config.php bacula-web/application/config/
cp -pv bacula-web-beforeupgrade/application/assets/protected/* bacula-web/application/assets/protected/

I also ran these commands:
chown -v apache: bacula-web/application/config/config.php
chown -Rv apache: bacula-web/application/assets/protected

Not listed in the upgrade documentation I also ran these commands (to match previous install):
chown -Rv apache: /var/www/lighttpd/bacula-web/application/views/cache
chown root:root /var/www/lighttpd/bacula-web/application/assets/protected/.htaccess
chmod 644 /var/www/lighttpd/bacula-web/application/assets/protected/.htaccess

It also looks like write access is enabled in the tarball for the group, so I also ran this command to match previous installation:
chmod -Rv g-w /var/www/lighttpd/bacula-web

This makes older (working version) match new version with mode and owner.

I now get an HTTP/500 error when trying to access the home page.

**To Reproduce**
Follow upgrade instructions listed above

**Expected behavior**
see bacula-web login screen

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: CentOS 7.9
 - Browser Brave
 - Version 
 - PHP version [7.4.33]

**Additional context**
It looks like directory structure might have changed since 8.9.0?  It does not look like upgrade instructions have changed.  Not sure what else to do.

**Comment by dfranco** [comment]
Hello @sruckh ,

Thanks for the bug report.

I'll double check if the upgrade procedure is still accurate, thanks for pointing that out.

I see two issues based on the details you've provided.

The first one, is the PHP version you're using.
As stated in v9.0.0 release note (https://github.com/bacula-web/bacula-web/releases/tag/v9.0.0), PHP 7.4 is not supported anymore and you should use PHP 8.0 at least.
There are several technical reasons to enforce PHP >= 8.0, one of these is that PHP 7.4 is EOL (see https://www.php.net/supported-versions.php).

You could also use official Bacula-Web Docker image which use PHP 8.0
https://hub.docker.com/r/baculaweb/bacula-web

The second potential issue is that you're downloading the tar.gz from GitHub release which is a simple archive of the git repository where nothing is installed except Bacula-Web source code, it miss all the Composer dependencies in it.
You need Composer installer using Centos official repo, or simply use instructions provided in the documentation (https://docs.bacula-web.org/en/latest/02_install/installcomposer.html#install-composer).
If Composer package is too old or not available for Centos 7.9 (didn't try yet), you can use instructions provider here https://getcomposer.org/download/.

I'll take a look at the upgrade documentation and will make some fixes if needed.

Hope it helps

**Comment by dfranco** [comment]
Fixed missing instructions while upgrading, thanks again for the bug report @sruckh

**Comment by dfranco** [comment]
@sruckh if it can help you upgrading PHP on Centos 7.9.

https://rpms.remirepo.net/wizard/
