### ISSUE TITLE
Paths in view partials should include basepath

### ISSUE THREAD

**Issue by BoresXP** [bacula-web/bacula-web#210]
**Describe the bug**
To allow placing bacula-web into subdirectory paths in view partials should include basepaths. Otherwise static resources are always requested from website root instead of subdirectory.

**To Reproduce**
1. Install bacula-web into subdirectory.
2. Set basepath in config.
3. subdirectory in browser.
4. Static resources are not loaded.

**Expected behavior**
Bacula-web should should be served fine even from subdir

**Additional context**
Will create a PR soon.

**Comment by dfranco** [comment]
Hi @BoresXP ,

Thanks for the bug report and PR.

I'll have a look and keep you posted.

**Comment by dfranco** [comment]
@BoresXP , found other places where base_path() is missing, I'll fix it on my side.

Also, please use conventional commit, something like

```
fix: missing base path in twig templates

Add missing base_path() in Twig partials.

Resolve: #210
```

**Comment by BoresXP** [comment]
@dfranco, I've changed PR message. Should be OK now.

**Comment by dfranco** [comment]
> @dfranco, I've changed PR message. Should be OK now.

@BoresXP The commit message on the PR is still the same.

> 
> How can I force failed failed check to run again on my PR?

No need to force checks on the PR, if you git push it runs automatically.

If you need a hand, just tell me.
