### ISSUE TITLE
Wrong return type in App\Table\VolumeTable::getDiskUsage()

### ISSUE THREAD

**Issue by gribnut** [bacula-web/bacula-web#231]
**Describe the bug**
When viewing "Director(s)" report, throws exception due to int returned from VolumeTable->getDiskUsage() in VolumeTable.php.

**To Reproduce**
1. Go to 'Reports->Director(s)'
2. See error

**Expected behavior**
No error/exception.  VolumeTable->getDiskUsage() return string instead of int.

**Screenshots**
Error:
App\Table\VolumeTable::getDiskUsage(): Return value must be of type string, int returned
File: bacula-web-9.5.1/application/Controller/DirectorController.php on line 102 in function App\Table\VolumeTable->getDiskUsage

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04.1
 - Browser: Chrome
 - Version: 9.5.1
 - PHP version: 8.3.6
 - Bacula 13.04 using sqlite3 database

**Additional context**
Possible that issue may be specific to Bacula 13.04 and/or using sqlite3 database.  Should be safe to wrap return of VolumeTable->getDiskUsage() with strval() to ensure value is a string in case there is mix of types in different versions of Bacula or database type.

    // Sample code change
    public function getDiskUsage(): string
    {
        $fields = ['SUM(Media.VolBytes) as bytes_size'];
        $statment = [
            'table' => $this->tablename,
            'fields' => $fields
        ];

        // Run SQL query
        $result = $this->run_query(CDBQuery::get_Select($statment));

        $result = $result->fetch();
        return strval($result['bytes_size']);
    }

**Comment by dfranco** [comment]
Thanks for this bug report @gribnut 

Sorry, but I need to book a bit of time to reproduce the bug you're facing

In the meantime, could you answer few of my questions pls ?

- why using SQlite against MySQL/MariaDB or postgreSQL ?
- how did you install Bacula (packages, from source, etc.) ?

Thanks for your feedback

Best,

**Comment by dfranco** [comment]
Thanks for your feedback @gribnut 

It looks like Ubuntu is still proving Bacula packages with SQLite catalog support ...

Are you interested to test next major release ?

**Comment by gribnut** [comment]
Hmm, I didn't realize SQLite has been deprecated in Bacula for some time.  Looks like I need to migrate to either MySQL or PostgreSQL before driver is dropped entirely from Bacula.  Regardless happy to help w/ testing your next major release.

**Comment by dfranco** [comment]
That would be great.

I'll get back to you once I have a proper documentation, or at least "getting started" guide for release 10.0.0

**Comment by dfranco** [comment]
Hi @gribnut ,

After deeper research, I've found out that SQLite seem to be still supported by the community, and by Bacula Systems too.

Bacula 15.0.2 release notes has this
```
15Nov23
 - Fix #2699 About SQLite update script
```
So I may bring back SQLite support in this project.

I'll keep you posted about this too.

Best,
