### ISSUE TITLE
Error with postgreSQL using JobFiles report page

### ISSUE THREAD

**Issue by machadommm** [bacula-web/bacula-web#39]
Hi, When i try to click the File hyperlink column link (as show):

![image](https://user-images.githubusercontent.com/51215190/58667688-1c0df100-830d-11e9-90dd-678b7fe36775.png)

It Happens:

![image](https://user-images.githubusercontent.com/51215190/58667807-6d1de500-830d-11e9-8f1a-c8b2d02b7bbd.png)

Some help?

Cheers,

Machado

**Comment by dfranco** [comment]
Hi @machadommm ,

Thanks for this bug report.

I'll try to reproduce it and fix it for next release

**Comment by unforgiving** [comment]
Hi, any news about this issue?
I've the same issue using Postgres. I'm using Ubuntu 18.08 and Postgres 10.7 and Apache 2.4.29.
Thanks in advance.

**Comment by dfranco** [comment]
Hi @unforgiving ,

I'll work on a fix asap, please be patient.

**Comment by unforgiving** [comment]
Hi @dfranco, 

Sorry, I don't wanted to rush you, I was just reporting that I have the same issue and provide some more details, take your time. Thank you.

**Comment by dfranco** [comment]
Hi @machadommm & @unforgiving,

It took me time to find a moment to investigate and fix this issue.
But at least it's fixed now.

develop branch include the fix, I'll make a small release asap.

Best regards

**Comment by guillep2k** [comment]
> 
> 
> Hi @machadommm & @unforgiving,
> 
> It took me time to find a moment to investigate and fix this issue.
> But at least it's fixed now.
> 
> develop branch include the fix, I'll make a small release asap.
> 
> Best regards

I've downloaded and replaced just these two files on my 8.3.1 installation: they've worked for me. Thank you!

**Comment by machadommm** [comment]
Hi Davide, 

Working very well now! 

Thank you very much!!! 


Mauro Macedo .:Machado:. 
Mobile: +55 021-98879-8654 


De: "Davide Franco" <notifications@github.com> 
Para: "bacula-web/bacula-web" <bacula-web@noreply.github.com> 
Cc: "mauro@machado.eti.br" <mauro@machado.eti.br>, "Mention" <mention@noreply.github.com> 
Enviadas: Segunda-feira, 15 de julho de 2019 13:41:05 
Assunto: Re: [bacula-web/bacula-web] Error with postgreSQL using JobFiles report page (#39) 



Hi [ https://github.com/machadommm | @machadommm ] & [ https://github.com/unforgiving | @unforgiving ] , 

It took me time to find a moment to investigate and fix this issue. 
But at least it's fixed now. 

develop branch include the fix, I'll make a small release asap. 

Best regards
