### ISSUE TITLE
Invalid date format inside DateTimeUtil::Get_Elapsed_Time

### ISSUE THREAD

**Issue by bulanh** [bacula-web/bacula-web#42]
When input `$end_time` is not set, function uses wrong format for creating `$end` variable used for calculating diff (should be `'Y-m-d H:i:s'`, but is `'Y-m-d H:m:i'`). 
Moreover, this formatting is unnecessary, since simple `$end = new DateTime()` would suffice.

**Comment by dfranco** [comment]
Hello @bulanh ,

First of all, sorry for my late answer.

Just a quick feedback about your pull request.

$end_time parameter in function DateTimeUtil::Get_Elapsed_Time($start_time, $end_time) is not optional, $end_time parameter should be always provided.

You're change is ok, thanks for it.

Cheers
