### ISSUE TITLE
List of files too short, not configurable.

### ISSUE THREAD

**Issue by marcogaio** [bacula-web/bacula-web#44]
Cool project to monitor Bacula! Simple and effective!
But one function i use heavily is 'find the file', because users rarely know exactly the filename they have lost, and where was.
But by default on job files page (index.php?page=jobfiles&jobId=XXXX&paginationCurrentPage=1) only 10 files per page are printed.

Attached a patch that add this parameters to configuration (config.php), eg:
`
$config['rows_per_page'] = 10000;
`
Thanks.
[bacula-web.diff.gz](https://github.com/bacula-web/bacula-web/files/3605477/bacula-web.diff.gz)

**Comment by dfranco** [comment]
Hi @marcogaio ,
Thanks for your bug report and kind words about the project.
What about having a "file search" form in Job files report instead ?
Best regards

**Comment by marcogaio** [comment]
> Thanks for your bug report and kind words about the project.
Thanks to you for the project!

> What about having a "file search" form in Job files report instead ?
Would be marvellous!

**Comment by dfranco** [comment]
Hi @marcogaio,

The requested feature (#54) has been implemented in the dev code, it will be available with next release.

Thanks for the great idea.

Best,

**Comment by dfranco** [comment]
Hi @marcogaio,

The requested feature (#54) has been implemented in the dev code, it will be available with next release.

Thanks for the great idea.

Best,
