### ISSUE TITLE
FreeBSD + NGINX  PHP Fatal error

### ISSUE THREAD

**Issue by SkyLakeRT** [bacula-web/bacula-web#45]
Hi everyone!
I have freebsd:
`FreeBSD okhsrv 12.0-RELEASE-p2 FreeBSD 12.0-RELEASE-p2 GENERIC  amd64`

I downloaded latest version bacula-web via git. Make configure nginx, he is  good run, php-fpm good run, but i have error from (error) log file nginx. Error message full:
```
2019/09/18 17:53:07 [error] 58551#100743: *715 FastCGI sent in stderr: "PHP message: PHP Warning:  require_once(vendor/autoload.php): failed to open stream: No such file or directory in /usr/local/www/bacula-new-web/core/global.inc.php on line 19
PHP message: PHP Fatal error:  require_once(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/local/share/pear') in /usr/local/www/bacula-new-web/core/global.inc.php on line 19" while reading response header from upstream, client: 193.169.255.102, server: MYDOMAIN, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/tmp/php-fpm.sock:", host: "MYDOMAIN"
```
Here is shot info:
`PHP message: PHP Fatal error:  require_once(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/local/share/pear') in /usr/local/www/bacula-new-web/core/global.inc.php on line 19`

File /usr/local/www/bacula-new-web/core/global.inc.php for string 19 ::
...
` require_once 'vendor/autoload.php';`
...

If to comment this string, have other errors.
What can i do for this?

**Comment by dfranco** [comment]
Hello @SkyLakeRT,

Make sure you've Composer installed and run this command from root of Bacula-Web path
`$ cd /usr/local/www/bacula-new-web` 
`$ composer install --no-dev`

Hope it helps

**Comment by SkyLakeRT** [comment]
> Hello @SkyLakeRT,
> 
> Make sure you've Composer installed and run this command from root of Bacula-Web path
> `$ cd /usr/local/www/bacula-new-web`
> `$ composer install --no-dev`
> 
> Hope it helps

I solved this problem. Downloaded tar archive from web site.
unarchive etc...
