### ISSUE TITLE
PHP 7.2 support

### ISSUE THREAD

**Issue by pqvindesland** [bacula-web/bacula-web#47]
Hi 

Is there any plans for support for php 7.2? 

Regards
Per

**Comment by dfranco** [comment]
Hi @pqvindesland,

the answer is yes, net Bacula-Web major version release will have full support for latest PHP versions.
https://www.php.net/supported-versions.php

Did you encounter any issue with PHP 7.2 ?

**Comment by pqvindesland** [comment]
Cool so will 8.3.3 work with php 7.2?

**Comment by pqvindesland** [comment]
I tried a month or so ago but it didn't work with 7.2 I can't remember the errors I got

**Comment by dfranco** [comment]
Hi @pqvindesland ,

8.3.3 has already been released, it they're any issue with PHP 7.2 this is something I'll fix for next major release 8.4.0.

I'll make some tests with PHP 7.2 and create one or more issues here if required.

**Comment by dfranco** [comment]
I'm running bacula-web on Debian 10 (Buster) with PHP 7.3.14-1 without warning and/errors

**Comment by dfranco** [comment]
Hello @pqvindesland,

The documentation has been updated (supported PHP version up to 7.3), I'm closing this bug report.

Thanks for your bug report :)
