### ISSUE TITLE
PHP SQLite support not found on Linux Mint

### ISSUE THREAD

**Issue by mmiat** [bacula-web/bacula-web#48]
I've copied and extracted archive, modified config.php
when I access bacula-web I've this error:

A problem with the description below happen
Problem: PHP SQLite support not found

but SQLite module are available and enabled (I can see it in phpinfo)

however, I want to use MySQL, not SQLite, I've to have SQLite enabled in any case?

**Comment by dfranco** [comment]
Hi @mmiat ,
As mentioned in the page below, SQLite is required for user(s) authentication.
http://docs.bacula-web.org/en/v8.3.3/02_install/requirements.html#general-requirements
Can you share more details about the system you're running Bacula-Web on ?
I'd need PHP version, used web server (Apache or Nginx), OS & version (Debian,Ubuntu,Centos,etc.) web server error log might be helpful too.
Best,

**Comment by mmiat** [comment]
Sistema: Linux Mint 19.3 Cinnamon
Apache 2
PHP 7.2.24-0ubuntu0.18.04.2
later I'll try to attach also log from webserver

**Comment by dfranco** [comment]
Thanks @mmiat ,

I'll try to reproduce it on my side and let you know.

Best,

**Comment by dfranco** [comment]
Hello @mmiat ,

I've installed a clean server running Linux Mint 19.3 and haven't found any problem with PHP Sqlite support (see test page screenshot below).

<img width="1118" alt="Screenshot 2020-02-26 at 07 15 24" src="https://user-images.githubusercontent.com/482177/75317360-175c7600-5868-11ea-8de0-5dab4750c96f.png">

I'll fix current Bacula-Web documentation but, make sure you've installed the package below
`php-sqlite3`

Hope it helps.

Best regards

**Comment by dfranco** [comment]
Any feedback about my last comment @mmiat ?

**Comment by mmiat** [comment]
sorry but I've had no time, in Italy now there is caos....

**Comment by dfranco** [comment]
Hi @mmiat ,
no problem, it's kind of chaos here too ...
good luck and best wishes to you, your friends and your family.

**Comment by dfranco** [comment]
Hi @mmiat,

I hope you and your family are safe and in good health.

PHP Sqlite support **must** be installed as user authentication use it to store users informations.
Bacula-Web documentation will be updated for next release.

Thanks for your bug report, take care.

Best,

Davide
