### ISSUE TITLE
Broken dowload link in Readme.md

### ISSUE THREAD

**Issue by mmiat** [bacula-web/bacula-web#49]
in home page there is a link to https://www.bacula-web.org/download-latest-version/
it gives 404 error

**Comment by dfranco** [comment]
Hi @mmiat 

Good catch, thank you very much.

I'll fix it for next version.

Best,

**Comment by dfranco** [comment]
The link to download page has been fixed in dev branch, the Readme.md will be fixed on next release.

Thanks again @mmiat  for the bug report.
