### ISSUE TITLE
Job files report

### ISSUE THREAD

**Issue by pablomkz** [bacula-web/bacula-web#50]
Hi,
Job files report doesn´t appear in menu; it's a bug or just an installation error?
Thank you for your reponse...!!!

![image](https://user-images.githubusercontent.com/22173332/73542845-5b4c8e80-4414-11ea-97ee-75da1644e1ef.png)

**Comment by dfranco** [comment]
Hi @pablomkz 

Thanks for your question.

The "Job files" report is available from Reports / Backup job report.

Once you've selected a client, you'll see latest backup jobs and then, be able to display the job files report from here.

You can find a chapter in the documentation which explain the feature [here](http://docs.bacula-web.org/en/v8.3.3/01_about/features.html#job-files).

By the way, I just found out that the documentation is not up to date, I'll update it for next release.

For next Bacula-Web release, I'll improve the way "Job files" report will be available. IMHO, it's a bit "hidden" in current version.

If I wan't clear enough, please get back to me and I'll try to help you. 

Best,

**Comment by pablomkz** [comment]
Hi Davide,

Backup Job Report have three options periods: Last week, Last two weeks, Last month.
But my backup jobs are older than this; how can I see it?

Thank you for your support...!!!!

Pablo

**Comment by dfranco** [comment]
Hi @pablomkz 

These three period are hard-coded, I propose to have another field which allow you to define a custom period, like for the job history report.

But this is a completely different topic than the one you've started in this bug report.

I'll create a separate feature request for that if you agree.

Best,

**Comment by pablomkz** [comment]
Hi Davide,

Ok, I agree with your proposal.

I´m really thank you with your support.

Best,
Pablo

**Comment by dfranco** [comment]
Hi @pablomkz 

Thanks to you for helping with the project.

I'll do my best to include this new feature later this year.

Best,

Davide

**Comment by dfranco** [comment]
#51 feature request created, feel free to comment if needed.

**Comment by dfranco** [comment]
Moving this one to v8.8.0

**Comment by dfranco** [comment]
Specific feature #51 created, closing this one
