### ISSUE TITLE
Users authentication database not found.

### ISSUE THREAD

**Issue by deagcg** [bacula-web/bacula-web#53]
### Debug
**File**: /var/www/bacula-web/core/app/userauth.class.php
**Line**: 68
**Code**: 0

### Exception trace
```
File: /var/www/bacula-web/core/app/webapplication.class.php on line 49 in function UserAuth->checkSchema
File: /var/www/bacula-web/core/app/webapplication.class.php on line 136 in function WebApplication->setup
File: /var/www/bacula-web/index.php on line 21 in function WebApplication->run
```

**Comment by dfranco** [comment]
Hello @deagcg ,

Can you ensure that you've run the few steps documented in the link below please ?
http://docs.bacula-web.org/en/v8.3.3/02_install/finalize.html

Hope it helps

Best regards

Davide

**Comment by deagcg** [comment]
Hi! @dfrnaco, thank you very much for your response. It was helpful.

Again thank you very much.

**Comment by deagcg** [comment]
Another question.
When I proceed to create the user, it shows this message.

> It's now time to setup the application back-end database
> Please note that all informations stored in the user database will be destroyed
> Can we proceed?

Would you delete the database I have from Bacula? Or create a database (SQLite that requires) for authentication? I'm using PostgreSQL for the Bacula database

**Comment by deagcg** [comment]
Another problem, I changed the language as indicated in the tutorial. Still it keeps the default language. These are my settings.

![image](https://user-images.githubusercontent.com/61913210/76166682-bde12a80-6136-11ea-895e-8a49e903a6c5.png)

```
<?php

$config['show_inactive_clients'] = true;
$config['hide_empty_pools'] = false;
$config['enable_users_auth'] = true;
$config['debug'] = false;
$config['language'] = 'es_ES';

$config[0]['label'] = 'Prod Server';
$config[0]['host'] = 'localhost';                                                                                          
$config[0]['login'] = 'bacula';
$config[0]['password'] = 'bacula';
$config[0]['db_name'] = 'bacula';
$config[0]['db_type'] = 'pgsql';
$config[0]['db_port'] = '5432';

```

**Comment by dfranco** [comment]
> Another question.
> When I proceed to create the user, it shows this message.
> 
> > It's now time to setup the application back-end database
> > Please note that all informations stored in the user database will be destroyed
> > Can we proceed?
> 
> Would you delete the database I have from Bacula? Or create a database (SQLite that requires) for authentication? I'm using PostgreSQL for the Bacula database

Hi @deagcg ,

Bacula-Web setup will never, ever touch your Bacula catalog.

This warning is only about the back-end user database.

P.S: in a future release, I'll improve the bwc tool to give more options and details.

Best,

**Comment by dfranco** [comment]
> Another problem, I changed the language as indicated in the tutorial. Still it keeps the default language. These are my settings.
> 
> ![image](https://user-images.githubusercontent.com/61913210/76166682-bde12a80-6136-11ea-895e-8a49e903a6c5.png)
> 
> ```
> <?php
> 
> $config['show_inactive_clients'] = true;
> $config['hide_empty_pools'] = false;
> $config['enable_users_auth'] = true;
> $config['debug'] = false;
> $config['language'] = 'es_ES';
> 
> $config[0]['label'] = 'Prod Server';
> $config[0]['host'] = 'localhost';                                                                                          
> $config[0]['login'] = 'bacula';
> $config[0]['password'] = 'bacula';
> $config[0]['db_name'] = 'bacula';
> $config[0]['db_type'] = 'pgsql';
> $config[0]['db_port'] = '5432';
> ```

Make sure you've the right locale available by running this command below
`$ locale -a`
also make sure you've restarted Apache service.

Hope it helps.

**Comment by dfranco** [comment]
> Hi! @dfrnaco, thank you very much for your response. It was helpful.
> 
> Again thank you very much.

You're welcome, always a pleasure to help community users :)

**Comment by deagcg** [comment]
> > Another question.
> > When I proceed to create the user, it shows this message.
> > > It's now time to setup the application back-end database
> > > Please note that all informations stored in the user database will be destroyed
> > > Can we proceed?
> > 
> > 
> > Would you delete the database I have from Bacula? Or create a database (SQLite that requires) for authentication? I'm using PostgreSQL for the Bacula database
> 
> Hi @deagcg ,
> 
> Bacula-Web setup will never, ever touch your Bacula catalog.
> 
> This warning is only about the back-end user database.
> 
> P.S: in a future release, I'll improve the bwc tool to give more options and details.
> 
> Best,

Understood, thanks for clearing up the doubt.
As support I want to help this community also, creating a document with the installation but in Spanish.

**Comment by deagcg** [comment]
> > Another problem, I changed the language as indicated in the tutorial. Still it keeps the default language. These are my settings.
> > ![image](https://user-images.githubusercontent.com/61913210/76166682-bde12a80-6136-11ea-895e-8a49e903a6c5.png)
> > ```
> > <?php
> > 
> > $config['show_inactive_clients'] = true;
> > $config['hide_empty_pools'] = false;
> > $config['enable_users_auth'] = true;
> > $config['debug'] = false;
> > $config['language'] = 'es_ES';
> > 
> > $config[0]['label'] = 'Prod Server';
> > $config[0]['host'] = 'localhost';                                                                                          
> > $config[0]['login'] = 'bacula';
> > $config[0]['password'] = 'bacula';
> > $config[0]['db_name'] = 'bacula';
> > $config[0]['db_type'] = 'pgsql';
> > $config[0]['db_port'] = '5432';
> > ```
> 
> Make sure you've the right locale available by running this command below
> `$ locale -a`
> also make sure you've restarted Apache service.
> 
> Hope it helps.

Effectively.
It had only es_VE but it is not_ES.

Again, thank you very much Davide.

**Comment by dfranco** [comment]
> > > Another question.
> > > When I proceed to create the user, it shows this message.
> > > > It's now time to setup the application back-end database
> > > > Please note that all informations stored in the user database will be destroyed
> > > > Can we proceed?
> > > 
> > > 
> > > Would you delete the database I have from Bacula? Or create a database (SQLite that requires) for authentication? I'm using PostgreSQL for the Bacula database
> > 
> > 
> > Hi @deagcg ,
> > Bacula-Web setup will never, ever touch your Bacula catalog.
> > This warning is only about the back-end user database.
> > P.S: in a future release, I'll improve the bwc tool to give more options and details.
> > Best,
> 
> Understood, thanks for clearing up the doubt.
> As support I want to help this community also, creating a document with the installation but in Spanish.

Hi @deagcg ,
Please create another bug here on GitHub so we focus on that topic.
Best regards

**Comment by dfranco** [comment]
> > > Another problem, I changed the language as indicated in the tutorial. Still it keeps the default language. These are my settings.
> > > ![image](https://user-images.githubusercontent.com/61913210/76166682-bde12a80-6136-11ea-895e-8a49e903a6c5.png)
> > > ```
> > > <?php
> > > 
> > > $config['show_inactive_clients'] = true;
> > > $config['hide_empty_pools'] = false;
> > > $config['enable_users_auth'] = true;
> > > $config['debug'] = false;
> > > $config['language'] = 'es_ES';
> > > 
> > > $config[0]['label'] = 'Prod Server';
> > > $config[0]['host'] = 'localhost';                                                                                          
> > > $config[0]['login'] = 'bacula';
> > > $config[0]['password'] = 'bacula';
> > > $config[0]['db_name'] = 'bacula';
> > > $config[0]['db_type'] = 'pgsql';
> > > $config[0]['db_port'] = '5432';
> > > ```
> > 
> > 
> > Make sure you've the right locale available by running this command below
> > `$ locale -a`
> > also make sure you've restarted Apache service.
> > Hope it helps.
> 
> Effectively.
> It had only es_VE but it is not_ES.
> 
> Again, thank you very much Davide.

Again it's always a pleasure to help

I'll try to make the documentation clearer for next release.

Best regards

**Comment by fabiolima85** [comment]
Helo!

For me the same error message is appearing.
I tried to run the procedure from the link http://docs.bacula-web.org/en/latest/02_install/finalize.html, but when I run the command sudo -u apache php bwc setupauth
the following message appears:
sudo: bwc: command not found

I'm using the following environment:
Cento 7
MariaDB 10.6.2
Bacula 11.0.1
Bacula-Web 8.4.1

**Comment by dfranco** [comment]
hello @fabiolima85 ,

Can you provide me the output of the root folder where you've installed Bacula-Web please ?

For example
`ls -l /var/www/bacula-web`

**Comment by dfranco** [comment]
Documentation updated (see #64)
