### ISSUE TITLE
Job files search returns SQL syntax error

### ISSUE THREAD

**Issue by HonzaKoren** [bacula-web/bacula-web#55]
In version 8.4.0 there is a bug in Job files count files query rendering an error page instead of found files.
The problem is in application/model/jobfiles.php on row 49, where is hardcoded semicolon. Next to it any added search condition makes query syntactically incorrect.
https://github.com/bacula-web/bacula-web/blob/139d99083248375f8f612b881faf30b4a5bfbd07/application/models/jobfiles.model.php#L49

Here is a quick fix diff:
<pre>
diff --git a/application/models/jobfiles.model.php b/application/models/jobfiles.model.php
index 158950b..d888bdc 100644
--- a/application/models/jobfiles.model.php
+++ b/application/models/jobfiles.model.php
@@ -46,13 +46,15 @@ class JobFiles_Model extends CModel {
                        WHERE File.JobId = $jobId 
                        AND  Path.PathId = File.PathId 
                        AND  Filename.FilenameId = File.FilenameId 
-            AND  Job.JobId = File.JobId; ";
+            AND  Job.JobId = File.JobId ";
 
       // Filter by filename if requested
       if( !empty($filename)) {
          $sql_query .= "AND Filename.Name LIKE '%$filename%' ";
       }
 
+      $sql_query .= ";";
+
       $result = $this->run_query($sql_query);
 
                $used_types = $result->fetchAll();
</pre>

**Comment by HonzaKoren** [comment]
If you could consider the following SQL search query improvement, I think I'd not be the only one appreciating it.
This would query both, the path and the filename against a given path sample as well as against exact file match including path from root.
Here is a full diff.
<pre>
diff --git a/application/models/jobfiles.model.php b/application/models/jobfiles.model.php
index 158950b..ba59bbc 100644
--- a/application/models/jobfiles.model.php
+++ b/application/models/jobfiles.model.php
@@ -17,7 +17,7 @@ class JobFiles_Model extends CModel {
         $where = array("File.JobId = $jobId");
 
         if( !empty($filename) ) {
-           $where[] = "Filename.Name LIKE '%$filename%'";
+           $where[] = "(Filename.Name LIKE '%$filename%' OR Path.Path LIKE '%$filename%' OR concat(Path.Path, '', Filename.Name) = '$filename')";
         }
         
         $orderby = 'File.FileIndex ASC';
@@ -46,13 +46,15 @@ class JobFiles_Model extends CModel {
                        WHERE File.JobId = $jobId 
                        AND  Path.PathId = File.PathId 
                        AND  Filename.FilenameId = File.FilenameId 
-            AND  Job.JobId = File.JobId; ";
+            AND  Job.JobId = File.JobId ";
 
       // Filter by filename if requested
       if( !empty($filename)) {
-         $sql_query .= "AND Filename.Name LIKE '%$filename%' ";
+         $sql_query .= "AND (Filename.Name LIKE '%$filename%' OR Path.Path LIKE '%$filename%' OR concat(Path.Path, '', Filename.Name) = '$filename') ";
       }
 
+      $sql_query .= ";";
+
       $result = $this->run_query($sql_query);
 
                $used_types = $result->fetchAll();
</pre>

**Comment by dfranco** [comment]
Hi @HonzaKoren ,

Thanks for the bug report.

If you could do a pull request it would be nice, bet back to me for instructions if needed.

**Comment by dfranco** [comment]
I had to fix a line in JobFiles_Model:countJobFiles() too

**Comment by dfranco** [comment]
Merged, thanks for the bug report.
