### ISSUE TITLE
Unable to get Bacula Dashboard 

### ISSUE THREAD

**Issue by dubeyumesh** [bacula-web/bacula-web#57]
Hello,

I am using centos 8 with php 5.6, I followed docs http://docs.bacula-web.org but getting below error code.

using below php and apache version.

Apache version and installed packages

Server version: Apache/2.4.37 (centos)
Server built:   Sep 15 2020 15:41:16

httpd-tools-2.4.37-21.module_el8.2.0+494+1df74eae.x86_64
httpd-2.4.37-21.module_el8.2.0+494+1df74eae.x86_64
centos-logos-httpd-80.5-2.el8.noarch
httpd-filesystem-2.4.37-21.module_el8.2.0+494+1df74eae.noarch
libnghttp2-1.33.0-3.el8_2.1.x86_64
mod_http2-1.11.3-3.module_el8.2.0+486+c01050f0.1.x86_64

php version  and installed packages
<img width="640" alt="baculaweb issue" src="https://user-images.githubusercontent.com/44396116/100707018-01b84600-33d0-11eb-945e-73c6e0a0746a.PNG">
<img width="640" alt="baculaweb issue" src="https://user-images.githubusercontent.com/44396116/100707073-18f73380-33d0-11eb-86f6-a7826573ebac.PNG">

PHP 5.6.40 (cli) (built: Sep 29 2020 11:31:13)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

php56-php-fpm-5.6.40-23.el8.remi.x86_64
php56-php-pecl-zip-1.19.2-1.el8.remi.x86_64
php56-libzip-1.7.3-2.el8.remi.x86_64
php56-php-pear-1.10.12-4.el8.remi.noarch
php56-php-bcmath-5.6.40-23.el8.remi.x86_64
php56-php-5.6.40-23.el8.remi.x86_64
php56-php-pecl-jsonc-1.3.10-3.el8.remi.x86_64
php56-php-process-5.6.40-23.el8.remi.x86_64
php56-3.0-1.el8.remi.x86_64
php56-php-mysqlnd-5.6.40-23.el8.remi.x86_64
php56-php-gd-5.6.40-23.el8.remi.x86_64
php56-php-common-5.6.40-23.el8.remi.x86_64
php56-php-pgsql-5.6.40-23.el8.remi.x86_64
php56-runtime-3.0-1.el8.remi.x86_64
php56-php-xml-5.6.40-23.el8.remi.x86_64
php56-php-cli-5.6.40-23.el8.remi.x86_64
php56-php-pdo-5.6.40-23.el8.remi.x86_64

Please help me on this issue ..

**Comment by dfranco** [comment]
Hello @dubeyumesh ,

You probably need to install libapache2-modphp (package name might differ depending on the os you're running).

Hope it helps

**Comment by sakrow** [comment]
Or you need to install PHP-FPM to use a Apache with her proxy and run PHP properly.

Here you have how to install FPM with nginx: https://www.cyberciti.biz/faq/install-php-7-x-on-centos-8-for-nginx/

To use in Apache you only need to add this:

```
<Directory "/<my-install-path>/">
        DirectoryIndex index.html index.php
        AllowOverride All
        Allow from All
        Options FollowSymLinks
        Require all granted

        <FilesMatch \.php$>
                SetHandler "proxy:unix:/var/run/<my-socket>.sock|fcgi://127.0.0.1"
        </FilesMatch>

    </Directory>
```
In you VirtualHost.

Hope it helps

**Comment by dfranco** [comment]
No feedback from @dubeyumesh , closing this issue.
