### ISSUE TITLE
On paginations of job and volume views

### ISSUE THREAD

**Issue by ibowen** [bacula-web/bacula-web#60]
Hi team,
Our job.view.php and volumne.view.php crash loading the full job and volumne lists. It looks like loading a long list of jobs blocks loading the css and js for paginations. Can they query data with limits before poplulating the web page?

**Comment by dfranco** [comment]
Hello @ibowen ,

Indeed, Bacula-Web rely on DataTables (https://www.datatables.net/) to paginate jobs and volumes list.

There's no limit (yet) on the SQL query for both jobs and volumes.

I'll see how I can improve it. If you have any dev skills, any PR would be greatly appreciated.

P.S: I'd be interested to know how many volumes and jobs you have in your bacula catalog btw.

**Comment by ibowen** [comment]
Hi Davide,
I changed the default filter to 'STATUS_RUNNING' instead of 'STATUS_ALL' to
avoid overwhelming the job view. I didn't find a similar way for the volume
page.

Our total jobs are around 150K.

**Comment by dfranco** [comment]
Hi @ibowen ,

You can try to filter volume report page by pool.

I'll work on a fix as soon as possible.

Best,

**Comment by dfranco** [comment]
@ibowen , a fix will be included in next release

**Comment by dfranco** [comment]
Hi @ibowen , this is now fixed in the code.

New release will be available by next hours :)
