### ISSUE TITLE
Could someone create docker-compose file for easy deployment this app?

### ISSUE THREAD

**Issue by SavaBlanko** [bacula-web/bacula-web#62]

**Comment by dfranco** [comment]
Hello @SavaBlanko ,

I do use a Docker image for development purpose which is not quiet ready to be use for "production".

If you are interested, that's something I might be able to share on Dockerhub.com.

Please let me know

**Comment by mikekuzak** [comment]
Also interested

**Comment by dfranco** [comment]
This is something I'll bring in the future for sure.

**Comment by dfranco** [comment]
This one is in the roadmap for next major release (9.0.0), unless there's an urgent bug to fix (security or general issue).

In the meantime, I might publish a "beta" version of the Docker image so community users can test it and give me some feedback before the official release.

Any volunteer out there ?

**Comment by dfranco** [comment]
Hi  @SavaBlanko & @mikekuzak 

2022 has been tough year (I'll share some thought in a post soon), really sorry for the delay on the Docker image topic.

I'm working hard to get v8.7.0 ready for the community, and I've been working on a Docker container image which the community could use.

It's still a work in progress, but it will be published really really soon :)
More details at https://hub.docker.com/r/baculaweb/bacula-web

Hope you'll enjoy it as much as I do

**Comment by dfranco** [comment]
Hi @SavaBlanko & @mikekuzak

Docker image and instructions are available [here](https://hub.docker.com/r/baculaweb/bacula-web)

**Comment by dfranco** [comment]
A new issue #153 has been created to update the documentation, I'm closing this one.
