### ISSUE TITLE
Baculum crash, but API and bconsole works

### ISSUE THREAD

**Issue by GammaPi** [bacula-web/bacula-web#72]
Prado\Exceptions\TInvalidOperationException
Description
Component 'MainSideBar' is evaluating an invalid expression '$this->Service->constructUrl('DirectorView', ['director' => $_SESSION['director']])' : [Notice] Undefined index: director (@line 1 in file /usr/share/baculum/htdocs/framework/pradosoft/prado/framework/TComponent.php(1229) : eval()'d code)..

Source File
/usr/share/baculum/htdocs/framework/pradosoft/prado/framework/TComponent.php (1234)

1223:      * @return mixed the expression result
1224:      */
1225:     public function evaluateExpression($expression)
1226:     {
1227:         $expression = $this->dyEvaluateExpressionFilter($expression);
1228:         try {
1229:             if (eval("\$result=$expression;") === false) {
1230:                 throw new \Exception('');
1231:             }
1232:             return $result;
1233:         } catch (\Exception $e) {
1234:             throw new TInvalidOperationException('component_expression_invalid', get_class($this), $expression, $e->getMessage());
1235:         }
1236:     }
1237: 
1238:     /**
1239:      * Evaluates a list of PHP statements.
1240:      *
1241:      * Behaviors may implement the function:
1242:      * <code>
1243:      *    public function dyEvaluateStatementsFilter($statements, $chain) {
1244:      *         return $chain->dyEvaluateStatementsFilter(str_replace('foo', 'bar', $statements)); //example
1245:      * }
1246:      * </code>

Stack Trace
#0 /usr/share/baculum/htdocs/framework/pradosoft/prado/framework/Web/UI/TCompositeLiteral.php(83): Prado\TComponent->evaluateExpression('$this->Service-...')
#1 /usr/share/baculum/htdocs/framework/pradosoft/prado/framework/Web/UI/TControl.php(1368): Prado\Web\UI\TCompositeLiteral->evaluateDynamicContent()
#2 /usr/share/baculum/htdocs/framework/pradosoft/prado/framework/Web/UI/TControl.php(1366): Prado\Web\UI\TControl->preRenderRecursive()
#3 /usr/share/baculum/htdocs/framework/pradosoft/prado/framework/Web/UI/TControl.php(1366): Prado\Web\UI\TControl->preRenderRecursive()
#4 /usr/share/baculum/htdocs/framework/pradosoft/prado/framework/Web/UI/TControl.php(1366): Prado\Web\UI\TControl->preRenderRecursive()
#5 /usr/share/baculum/htdocs/framework/pradosoft/prado/framework/Web/UI/TPage.php(233): Prado\Web\UI\TControl->preRenderRecursive()
#6 /usr/share/baculum/htdocs/framework/pradosoft/prado/framework/Web/UI/TPage.php(208): Prado\Web\UI\TPage->processNormalRequest(Object(Prado\Web\UI\THtmlWriter))
#7 /usr/share/baculum/htdocs/framework/pradosoft/prado/framework/Web/Services/TPageService.php(528): Prado\Web\UI\TPage->run(Object(Prado\Web\UI\THtmlWriter))
#8 /usr/share/baculum/htdocs/framework/pradosoft/prado/framework/Web/Services/TPageService.php(465): Prado\Web\Services\TPageService->runPage(Object(Dashboard), Array)
#9 /usr/share/baculum/htdocs/framework/pradosoft/prado/framework/TApplication.php(1190): Prado\Web\Services\TPageService->run()
#10 /usr/share/baculum/htdocs/framework/pradosoft/prado/framework/TApplication.php(382): Prado\TApplication->runService()
#11 /usr/share/baculum/htdocs/index.php(31): Prado\TApplication->run()
#12 {main}
2021-10-04 07:43 Apache/2.4.6 (CentOS) PHP/7.3.30 PRADO/4.0.1

**Comment by dfranco** [comment]
Hi @GammaPi ,

Sorry but this is a problem with [Baculum](https://baculum.app/), not Bacula-Web.

You should get in touch with the project maintainer, or post an email in Bacula users mailing list.

I'm closing this bug report.

Best regards

**Comment by phackwer** [comment]
I'm having exactly the same issue and this happens just after I've changed the passwords for admin.

![image](https://user-images.githubusercontent.com/4871786/170489128-8fa996fc-e732-46e2-b3e5-b18f7627c864.png)

**Comment by phackwer** [comment]
Oh, now I see, this is not the web app, sorry

**Comment by dfranco** [comment]
no problem
