### ISSUE TITLE
Bad sql query on Jobs report page using version 8.5.0

### ISSUE THREAD

**Issue by lrosenman** [bacula-web/bacula-web#93]
**Describe the bug**
A problem with the description below happen

Problem: SQLSTATE[42601]: Syntax error: 7 ERROR: LIMIT #,# syntax is not supported LINE 1: ...RE Job.JobStatus != 'xxxx' ORDER BY jobid DESC LIMIT 0,25 ^ HINT: Use separate LIMIT and OFFSET clauses.

File: /usr/local/www/bacula-web/core/app/cmodel.class.php
Line: 130
Code: 42601
**To Reproduce**
go to the jobs page for Bacula 11

**Expected behavior**
a jobs listing.
**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: FreeBSD 14.0-CURRENT
 - Browser Chrome Mac Version 96.0.4664.55 (Official Build) (x86_64)
 - Version [e.g. 8.5] 8.5.0
 - PHP version [e.g. 7.3] 7.4

**Additional context**

**Comment by lrosenman** [comment]
Also:
https://home.lerctr.org:8888/bacula-web/index.php?page=volumes

https://home.lerctr.org:8888/bacula-web/index.php?page=backupjob

PostgreSQL 11 for the Database, if that matters.

**Comment by dfranco** [comment]
Hello @lrosenman ,

Good catch, thanks for this bug report.

I'll fix it and release a new minor version by the end of today.

**Comment by dfranco** [comment]
Fixed #94

**Comment by dfranco** [comment]
@lrosenman: I've found another issue with Clients report page (see #95) , I'm working on it.

**Comment by dfranco** [comment]
@lrosenman : v8.5.1 will be available within the next few minutes.

Thanks again for your bug report.

**Comment by lrosenman** [comment]
Works great.  For your information, I'm now the port maintainer for bacula-web on FreeBSD.  I'll try to keep it more up2date.

**Comment by dfranco** [comment]
Thanks a lot for your feedback @lrosenman
