### ISSUE TITLE
BackupJob report error using PostgreSQL catalog

### ISSUE THREAD

**Issue by dfranco** [bacula-web/bacula-web#94]
Using Bacula 11.0.5 with PostgreSQL catalog, backup job report page display an error once form is submited

> SQLSTATE[HY093]: Invalid parameter number: :jobname

**Comment by dfranco** [comment]
This was due to missing PHP PDO bin parameters in Jobs_Model class

It is now fixed.

**Comment by lrosenman** [comment]
should I expect an 8.5.1 tag soon?

**Comment by lrosenman** [comment]
Also, does this fix the other 2 pages I referenced in #93 ?

**Comment by dfranco** [comment]
Yes, 8.5.1 will be released really soon.

This release will include fixes for the bugs you mentioned above too, and few others improvements too.

Best,
